// Command dnascan scans MIDI output directories and builds a DNA library.
//
// Usage:
//   go run ./cmd/dnascan/                              --scan ./generated + ./midi_output
//   go run ./cmd/dnascan/ --dir ./generated             --scan specific directory
//   go run ./cmd/dnascan/ --lib ./dna_library --rebuild --rebuild library from scratch
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/ShowerBandV/text2midi/internal/musicdna"
	"github.com/ShowerBandV/text2midi/internal/store"
)

func main() {
	dir := flag.String("dir", "", "Directory to scan (default: auto-detect ./generated and ./midi_output)")
	libDir := flag.String("lib", "./dna_library", "DNA library directory")
	rebuild := flag.Bool("rebuild", false, "Rebuild library from scratch")
	flag.Parse()

	lib := musicdna.NewLibrary(*libDir)

	if *rebuild {
		fmt.Printf("Rebuilding library at %s...\n", *libDir)
		os.RemoveAll(*libDir)
	}

	// Directories to scan.
	var scanDirs []string
	if *dir != "" {
		scanDirs = append(scanDirs, *dir)
	} else {
		for _, d := range []string{"./generated", "./midi_output"} {
			if info, err := os.Stat(d); err == nil && info.IsDir() {
				scanDirs = append(scanDirs, d)
			}
		}
	}

	if len(scanDirs) == 0 {
		fmt.Println("No directories found. Use --dir to specify.")
		os.Exit(1)
	}

	var totalFound, totalImported int

	for _, scanDir := range scanDirs {
		fmt.Printf("\nScanning %s...\n", scanDir)

		entries, err := os.ReadDir(scanDir)
		if err != nil {
			fmt.Fprintf(os.Stderr, "  Error: %v\n", err)
			continue
		}

		for _, entry := range entries {
			if !entry.IsDir() {
				continue
			}
			id := entry.Name()
			metaPath := filepath.Join(scanDir, id, "meta.json")
			dnaPath := filepath.Join(scanDir, id, "dna.json")

			// Check for store meta.json (generated by the server).
			metaData, err := os.ReadFile(metaPath)
			if err != nil {
				// Try dna.json directly.
				dnaData, err := os.ReadFile(dnaPath)
				if err != nil {
					continue
				}
				dna, err := musicdna.FromJSON(dnaData)
				if err != nil {
					continue
				}
				totalFound++
				if !dnaExists(lib, id) {
					saveDNA(lib, id, "unknown", dna, dnaData)
					totalImported++
				}
				continue
			}

			var record store.FileRecord
			if err := json.Unmarshal(metaData, &record); err != nil {
				continue
			}

			totalFound++

			if dnaExists(lib, id) {
				continue
			}

			// Try to load existing dna.json.
			dnaData, err := os.ReadFile(dnaPath)
			if err != nil {
				continue
			}

			dna, err := musicdna.FromJSON(dnaData)
			if err != nil {
				continue
			}

			saveDNA(lib, id, record.FileName, dna, dnaData)
			totalImported++
		}
	}

	fmt.Printf("\nDone: %d found, %d imported to %s\n", totalFound, totalImported, *libDir)

	if totalImported > 0 {
		listLibrary(lib)
	}
}

func dnaExists(lib *musicdna.Library, id string) bool {
	_, err := lib.Load(id)
	return err == nil
}

func saveDNA(lib *musicdna.Library, id, name string, dna *musicdna.MusicDNA, data []byte) {
	quality := musicdna.ScoreTemplate(dna)
	tmpl := &musicdna.DNATemplate{
		Name:    id,
		Style:   extractStyle(dna),
		DNA:     *dna,
		Quality: quality,
		Source:  name,
	}
	if err := lib.Save(tmpl); err != nil {
		fmt.Fprintf(os.Stderr, "  Failed to save %s: %v\n", id, err)
		return
	}
	styleInfo := extractStyle(dna)
	if styleInfo == "" {
		styleInfo = "unknown"
	}
	fmt.Printf("  Imported: %s (style=%s, quality=%.2f)\n", id, styleInfo, quality)
}

func extractStyle(dna *musicdna.MusicDNA) string {
	// Try to infer style from the key and structure.
	if dna == nil {
		return "unknown"
	}
	key := dna.Harmony.Key
	if key != "" {
		// Just use key as a proxy for now.
		return key
	}
	return "unknown"
}

func listLibrary(lib *musicdna.Library) {
	templates, err := lib.List("")
	if err != nil {
		return
	}
	fmt.Printf("\nDNA Library (%d templates):\n", len(templates))
	for _, t := range templates {
		fmt.Printf("  %-30s quality=%.2f style=%s\n", t.Name, t.Quality, t.Style)
	}
}
