// Package templates — built-in MusicDNA templates for common styles.
// Each template is a complete MusicDNA that the rule engine can instantiate.
// LLM only needs to select and tweak, not generate from scratch.
package templates

import "github.com/ShowerBandV/text2midi/internal/musicdna"

// All returns all built-in templates.
func All() []musicdna.Template {
	return []musicdna.Template{
		JPopBallad(),
		LoFiStudy(),
		EpicBattle(),
		RetroGame(),
	}
}

// GetByName returns a template by name, or nil.
func GetByName(name string) *musicdna.Template {
	for _, t := range All() {
		if t.Name == name {
			return &t
		}
	}
	return nil
}

// ─── JPop Ballad (周杰伦风格) ─────────────────────────────────────

func JPopBallad() musicdna.Template {
	return musicdna.Template{
		Name:        "jpop_ballad",
		Description: "周杰伦风格流行抒情，钢琴主导，温暖 nostalgia",
		DNA: musicdna.MusicDNA{
			Structure: musicdna.StructureDNA{
				Sections: []musicdna.Section{
					{Name: "intro", Bars: 2, Energy: 0.3, Density: 0.3, Instruments: []string{"piano"}},
					{Name: "verse", Bars: 4, Energy: 0.4, Density: 0.4, Instruments: []string{"piano", "bass", "drums_light"}},
					{Name: "pre", Bars: 2, Energy: 0.6, Density: 0.5, Instruments: []string{"piano", "bass", "drums", "strings"}},
					{Name: "chorus", Bars: 4, Energy: 0.8, Density: 0.7, Instruments: []string{"all"}},
					{Name: "bridge", Bars: 2, Energy: 0.4, Density: 0.3, Instruments: []string{"piano", "strings"}},
					{Name: "outro", Bars: 2, Energy: 0.2, Density: 0.2, Instruments: []string{"piano"}},
				},
			},
			Harmony: musicdna.HarmonyDNA{
				Key: "C major",
				Progression: []musicdna.ChordBar{},
				// Chord progression will be generated by LLM or random generator.
			},
			Motif: musicdna.MotifDNA{
				Notes:  []int{0, 2, 4, 3, 0}, // C-D-E-D-C pentatonic
				Rhythm: []float64{0.5, 0.5, 0.75, 0.25, 1.0},
			},
			Rhythm: musicdna.RhythmDNA{
				DrumPattern: "pop",
				Swing:       0.15,
			},
			Texture: musicdna.TextureDNA{
				InstrumentTimeline: map[string][]int{
					"piano":   {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15},
					"bass":    {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13},
					"drums":   {4, 5, 6, 7, 8, 9, 10, 11, 12, 13},
					"strings": {6, 7, 8, 9, 10, 11, 12, 13},
				},
			},
		},
	}
}

// ─── Lo-Fi Study ──────────────────────────────────────────────────

func LoFiStudy() musicdna.Template {
	return musicdna.Template{
		Name:        "lofi_study",
		Description: "Lo-fi chill beats, warm vinyl, simple piano loop",
		DNA: musicdna.MusicDNA{
			Structure: musicdna.StructureDNA{
				Sections: []musicdna.Section{
					{Name: "intro", Bars: 2, Energy: 0.2, Density: 0.2, Instruments: []string{"piano"}},
					{Name: "loop_a", Bars: 4, Energy: 0.4, Density: 0.4, Instruments: []string{"piano", "bass", "drums_light"}},
					{Name: "loop_b", Bars: 4, Energy: 0.5, Density: 0.5, Instruments: []string{"piano", "bass", "drums", "pad"}},
					{Name: "outro", Bars: 2, Energy: 0.2, Density: 0.2, Instruments: []string{"piano"}},
				},
			},
			Motif: musicdna.MotifDNA{
				Notes:  []int{0, 3, 5, 3, 0},
				Rhythm: []float64{1.0, 0.5, 0.5, 0.5, 1.0},
			},
			Rhythm: musicdna.RhythmDNA{
				DrumPattern: "lofi",
				Swing:       0.35,
			},
		},
	}
}

// ─── Epic Battle (JRPG) ───────────────────────────────────────────

func EpicBattle() musicdna.Template {
	return musicdna.Template{
		Name:        "epic_battle",
		Description: "Final Fantasy style boss battle, orchestral, driving",
		DNA: musicdna.MusicDNA{
			Structure: musicdna.StructureDNA{
				Sections: []musicdna.Section{
					{Name: "intro", Bars: 2, Energy: 0.5, Density: 0.4, Instruments: []string{"strings", "brass"}},
					{Name: "build", Bars: 4, Energy: 0.7, Density: 0.6, Instruments: []string{"strings", "brass", "timpani", "bass"}},
					{Name: "climax", Bars: 4, Energy: 0.95, Density: 0.9, Instruments: []string{"all"}},
					{Name: "bridge", Bars: 2, Energy: 0.5, Density: 0.4, Instruments: []string{"strings", "choir"}},
					{Name: "climax", Bars: 4, Energy: 0.95, Density: 0.9, Instruments: []string{"all"}},
					{Name: "outro", Bars: 2, Energy: 0.3, Density: 0.3, Instruments: []string{"strings"}},
				},
			},
			Motif: musicdna.MotifDNA{
				Notes:  []int{0, 2, 5, 7, 12},
				Rhythm: []float64{0.25, 0.25, 0.5, 0.25, 1.0},
			},
			Rhythm: musicdna.RhythmDNA{
				DrumPattern: "cinematic",
				Swing:       0.0,
			},
		},
	}
}

// ─── Retro Game (8-bit / Chiptune) ────────────────────────────────

func RetroGame() musicdna.Template {
	return musicdna.Template{
		Name:        "retro_game",
		Description: "8-bit chiptune, NES style, bouncy",
		DNA: musicdna.MusicDNA{
			Structure: musicdna.StructureDNA{
				Sections: []musicdna.Section{
					{Name: "intro", Bars: 2, Energy: 0.4, Density: 0.3, Instruments: []string{"lead"}},
					{Name: "loop_a", Bars: 4, Energy: 0.6, Density: 0.5, Instruments: []string{"lead", "bass", "drums"}},
					{Name: "loop_b", Bars: 4, Energy: 0.7, Density: 0.6, Instruments: []string{"lead", "bass", "drums", "chords"}},
					{Name: "outro", Bars: 2, Energy: 0.3, Density: 0.2, Instruments: []string{"lead"}},
				},
			},
			Motif: musicdna.MotifDNA{
				Notes:  []int{0, 4, 7, 12, 7, 4},
				Rhythm: []float64{0.25, 0.25, 0.5, 0.5, 0.25, 0.25},
			},
			Rhythm: musicdna.RhythmDNA{
				DrumPattern: "retro",
				Swing:       0.0,
			},
		},
	}
}
